### ISSUE TITLE
Overkoepelende Helm Chart

### ISSUE THREAD

**Issue by felixcicatt** [GPP-Woo/.github#8]
**Description (why)**
Om relatief eenvoudig alle componenten van het GPP WOO te kunnen installeren in een Kubernetes cluster van een gemeente, dient er een Helm Chart te komen waar al deze componenten in zitten.

**Acceptance criteria (what)**

**Specific details (how)**
De afspraak is dat Maykin deze Helm Chart zal realiseren.

**Test plan**

**Comment by sergei-maertens** [comment]
Inschatting S op basis van de bestaande PR
